// Copyright 2017-2021 @krypto-wealth/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@krypto-wealth/networks', version: '7.8.2' };
