// Copyright 2017-2021 @polkadot/networks authors & contributors
// SPDX-License-Identifier: Apache-2.0

//
// Auto-generated by yarn networks:sync (via scripts/fromSubstrate.mjs)
//
// This file should never be edited manually. Rather the process is as follow -
//
//   - make a PR to the upstream registry found at https://github.com/paritytech/ss58-registry/
//   - ensure the PR gets merged
//   - yarn networks:sync in this repo to sync
//
// Any manual changes to this file will make CI cron checks fail and will be
// lost when the registry is updated alongside the above sync.
//

import type { KnownSubstrate } from './types';

export const knownSubstrate: KnownSubstrate[] = [
  {
    decimals: [18],
    displayName: 'Kwe Testnet',
    network: 'kwe-testnet',
    prefix: 42,
    standardAccount: '*25519',
    symbols: ['KWE'],
    website: 'https://kwe.io/'
  },
  {
    decimals: [18],
    displayName: 'Kwe Mainnet',
    network: 'kwe-mainnet',
    prefix: 42,
    standardAccount: '*25519',
    symbols: ['KWE'],
    website: 'https://kwe.io/'
  }
];
